### ISSUE TITLE
Save/Load

### ISSUE THREAD

**Issue by JakobWitsch** [mj-studio-library/flutter-pencilkit#4]
Hi. In the description it states "Import/Export drawing data". Where are the available methods to do so?

Jakob

**Comment by mym0404** [comment]
hello, the import/export of data is not implemented yet.

**Comment by dkbast** [comment]
What would be needed to implement this? Can we use this issue to collect the necessary information to do the implementation? The widget is amazing, but without import/export its not really "useful" yet. 

Data structure:
https://developer.apple.com/documentation/pencilkit/pkdrawing
which consists of strokes:
https://developer.apple.com/documentation/pencilkit/pkdrawing/3595078-strokes

We can get and set the Drawing Data Structure from the canvas like so:
https://developer.apple.com/documentation/pencilkit/pkcanvasview/3229950-drawing

Here is a full tutorial which we could probably use to implement everything thats currently missing:
https://www.kodeco.com/12198216-drawing-with-pencilkit-getting-started

**Comment by frybitsinc** [comment]
hey I was wondering if you could merge my forked repo?
cause I just added save and reload feature on mine.
should I pr first...? or do something to do that? plz let me know what I can do, 
I would be honored if I could contribute to this project..!

**Comment by mym0404** [comment]
Sorry for inactiveness. Can you create a PR from your forked repository? I can review it @frybitsinc.

At first, I didn't implement Save/Load feature. Because I thought it can be related with file system and `Data` object in Swift and will be required complicated situations moreover.

**Comment by frybitsinc** [comment]
oh okay then I guess I will create pr right now...!
the way I thought was that... (long story short..)
If I could get the pkdrawing data from ios to the flutter side, then I could save it there, 
and also If I could get the pkdrawing data from flutter to ios side reloading would be possible, vice versa..?
anyways ..I think theres more thing to fix and improve..
to add import feature..(which i will be working on..sooner or later..)

**Comment by mym0404** [comment]
I am working on this now. Wait a minute please :)

**Comment by mym0404** [comment]
Published in `1.0.6` including save, load, get data. Thank you.
