### ISSUE TITLE
Building to device

### ISSUE THREAD

**Issue by richardchui** [mj-studio-library/flutter-pencilkit#5]
Working with the IOS simulator is fine, but when I try to build for a physical device, Xcode will fail with the message "missing module pencil_kit".  Are there steps I am missing?  Thanks!

**Comment by mym0404** [comment]
Did you install package pod correctly in iOS project?

Try `cd ios && pod deintegrate && pod install`

Or you can check `pencil_kit` placed correctly as a target in the pod project. 

![image](https://github.com/mj-studio-library/flutter-pencilkit/assets/33388801/734cec51-ed94-4408-b880-28a11f086071)
