### ISSUE TITLE
[Request] Pinch to zoom in/out & different sized canvas

### ISSUE THREAD

**Issue by isenbj** [mj-studio-library/flutter-pencilkit#9]
### Description

Would be nice to be able to zoom in/out of the view. Also to support bigger dimensions than the  container it is in.

### Device

None

**Comment by mym0404** [comment]
Hello, currently this is outside the scope of what this library does.

PKCanvasView is basically a UIScrollView, and you must directly implement an infinite size canvas through logic such as bounce.

You can check [sample](https://github.com/simonbs/InfiniteCanvas).

If you feel this is a problem for this library, please reply again.
